export const listOfCountries = [
  'Afghanistan',
  'Angola',
  'Albania',
  'United Arab Emirates',
  'Argentina',
  'Armenia',
  'Antarctica',
  'French Southern and Antarctic Lands',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Burundi',
  'Belgium',
  'Benin',
  'Burkina Faso',
  'Bangladesh',
  'Bulgaria',
  'Bahamas',
  'Bosnia and Herzegovina',
  'Belarus',
  'Belize',
  'Bolivia',
  'Brazil',
  'Brunei Darussalam',
  'Bhutan',
  'Botswana',
  'Central African Republic',
  'Canada',
  'Switzerland',
  'Chile',
  'China',
  "Côte d'Ivoire",
  'Cameroon',
  'Democratic Republic of the Congo',
  'Republic of the Congo',
  'Colombia',
  'Costa Rica',
  'Cuba',
  'Northern Cyprus',
  'Cyprus',
  'Czech Republic',
  'Germany',
  'Djibouti',
  'Denmark',
  'Dominican Republic',
  'Algeria',
  'Ecuador',
  'Egypt',
  'Eritrea',
  'Spain',
  'Estonia',
  'Ethiopia',
  'Finland',
  'Fiji',
  'Falkland Islands',
  'France',
  'Gabon',
  'United Kingdom',
  'Georgia',
  'Ghana',
  'Guinea',
  'The Gambia',
  'Guinea-Bissau',
  'Equatorial Guinea',
  'Greece',
  'Greenland',
  'Guatemala',
  'Guyana',
  'Honduras',
  'Croatia',
  'Haiti',
  'Hungary',
  'Indonesia',
  'India',
  'Ireland',
  'Iran',
  'Iraq',
  'Iceland',
  'Israel',
  'Italy',
  'Jamaica',
  'Jordan',
  'Japan',
  'Kazakhstan',
  'Kenya',
  'Kyrgyzstan',
  'Cambodia',
  'Republic of Korea',
  'Kosovo',
  'Kuwait',
  'Lao PDR',
  'Lebanon',
  'Liberia',
  'Libya',
  'Sri Lanka',
  'Lesotho',
  'Lithuania',
  'Luxembourg',
  'Latvia',
  'Morocco',
  'Moldova',
  'Madagascar',
  'Mexico',
  'Macedonia',
  'Mali',
  'Myanmar',
  'Montenegro',
  'Mongolia',
  'Mozambique',
  'Mauritania',
  'Malawi',
  'Malaysia',
  'Namibia',
  'New Caledonia',
  'Niger',
  'Nigeria',
  'Nicaragua',
  'Netherlands',
  'Norway',
  'Nepal',
  'New Zealand',
  'Oman',
  'Pakistan',
  'Panama',
  'Peru',
  'Philippines',
  'Papua New Guinea',
  'Poland',
  'Puerto Rico',
  'Dem. Rep. Korea',
  'Portugal',
  'Paraguay',
  'Palestine',
  'Qatar',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Western Sahara',
  'Saudi Arabia',
  'Sudan',
  'South Sudan',
  'Senegal',
  'Solomon Islands',
  'Sierra Leone',
  'El Salvador',
  'Somaliland',
  'Somalia',
  'Serbia',
  'Suriname',
  'Slovakia',
  'Slovenia',
  'Sweden',
  'Swaziland',
  'Syria',
  'Chad',
  'Togo',
  'Thailand',
  'Tajikistan',
  'Turkmenistan',
  'Timor-Leste',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Taiwan',
  'Tanzania',
  'Uganda',
  'Ukraine',
  'Uruguay',
  'United States',
  'Uzbekistan',
  'Venezuela',
  'Vietnam',
  'Vanuatu',
  'Yemen',
  'South Africa',
  'Zambia',
  'Zimbabwe',
]
